# Change these first
owner: rubywell # Your GitHub organization or username, where this repository lives
repo: rubywell-status-page # The name of this repository

sites:
  - name: Rubywell
    url: https://rubywell.com
    assignees:
      - oleh-rubywell
  - name: Rubywell Admin App
    url: https://admin.rubywell.com
    assignees:
      - oleh-rubywell
  - name: Rubywell Consumer App
    url: https://app.rubywell.com
    assignees:
      - oleh-rubywell

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.rubywell.com
  baseUrl: /rubywell-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rubywell Status Page
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Rubywell
      href: https://rubywell.com
    - title: Admin App
      href: https://admin.rubywell.com
    - title: Consumer App
      href: https://app.rubywell.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
